# Generated by Django 5.1.7 on 2025-04-21 16:27

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('NIN', models.IntegerField(unique=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('contact', models.IntegerField(default=0)),
                ('amount_due', models.IntegerField(default=0, null=True)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('salesagent_name', models.CharField(blank=True, max_length=25, null=True)),
                ('type_of_produce', models.IntegerField(blank=True, default=0, null=True)),
                ('tonnage', models.IntegerField(blank=True, default=0, null=True)),
                ('Dispatch_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_salesagent', models.BooleanField(default=True, null=True)),
                ('is_manager', models.BooleanField(default=True, null=True)),
                ('is_owner', models.BooleanField(default=True, null=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=25)),
                ('address', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_of_produce', models.DateField(auto_now_add=True)),
                ('tonnage', models.IntegerField(blank=True, default=0, null=True)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('name_of_dealer', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(max_length=25)),
                ('unit_price', models.IntegerField(default=0)),
                ('unit_cost', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField()),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('buyers_name', models.CharField(blank=True, max_length=35, null=True)),
                ('date_and_time', models.DateField(auto_now_add=True)),
                ('salesagent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('method_of_payment', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=255, null=True)),
                ('amount_received', models.FloatField(blank=True, default=0, null=True)),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stock')),
            ],
        ),
    ]
