# Generated by Django 5.1.7 on 2025-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyers_name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='sale',
            name='method_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='salesagent_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
