# Generated by Django 5.1.7 on 2025-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_credit_buyer_name_alter_sale_buyers_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='received_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
