# Generated by Django 5.1.7 on 2025-04-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stock_received_quantity_stock_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
