# Generated by Django 5.1.7 on 2025-04-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sale_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='NIN',
            field=models.CharField(blank=True, default='', max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
