# Generated by Django 5.1.7 on 2025-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_credit_nin_alter_credit_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
