# Generated by Django 5.1.7 on 2025-05-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_credit_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branch'),
        ),
    ]
