# Generated by Django 5.1.7 on 2025-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_assigned_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
